### ISSUE TITLE
webpack 5

### ISSUE THREAD

**Issue by sibelius** [entria/entria-fullstack#43]
We should keep on bleeding edge, let's experiment with webpack 5

https://github.com/webpack/webpack/releases/tag/v5.0.0-alpha.3

**Comment by PlayMa256** [comment]
It is a good idea, specially with a monorepo where we have different use cases (node and web). I would avoid using MemoryFileSystemCache due to the recent problems with memory-fs on other webpack projects.

Be aware that are some limitations on configuration changes (as stated on the full changelog). If we change config, cache is not invalidated, so it would be good to also have a way to either: invalidate cache automatically or delete cache with a npm script.
